[build]
builder = "NIXPACKS"

[deploy]
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 10
startCommand = "npm start"

[[services]]
[services.variables]
PORT = "3001"
NODE_ENV = "production"